version: '2'

services:

  rabbus:
    container_name: rabbus
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "5858:5858"
    volumes:
      - ./rabbus:/usr/src/app/rabbus
      - ./demos:/usr/src/app/demos
      - ./package.json:/usr/src/app/package.json
      - ./.jshintrc:/usr/src/app/.jshintrc
      - ./.jshintrc-specs:/usr/src/app/.jshintrc-specs
      - ./gruntfile.js:/usr/src/app/gruntfile.js
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    working_dir: /usr/src/app
    depends_on:
      - rabbitmq
    entrypoint:
      - entrypoint.sh
    networks:
      - rabbus-network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbus-network

networks:
    rabbus-network:
        driver: bridge
